/**
 * RAIOC IKL - Tier-1 & Master Real Estate Developers Knowledge Base
 */

import { AuthorityLevel } from '../provenance/provenance-engine.js';

export const developersData = [
  {
    id: 'dev_emaar',
    name: 'Emaar Properties',
    tier: 'TIER_1_GOVERNMENT_BACKED',
    rating: 'AAA',
    deliveryTrackRecordPercent: 97.4,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 1.2,
    flagshipProjects: ['Burj Khalifa', 'Dubai Hills Estate', 'Downtown Dubai', 'Emaar South'],
    renderUrl: 'https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Sovereign Master Communities, Ultra-Prime High-Rise Towers & Downtown District',
    provenance: {
      source: 'DFM Financial Disclosures & RERA Compliance Database',
      citation: 'Emaar Properties PJSC Audited Annual Disclosures 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_nakheel',
    name: 'Nakheel (Dubai Holding Real Estate)',
    tier: 'TIER_1_GOVERNMENT_BACKED',
    rating: 'AAA',
    deliveryTrackRecordPercent: 95.8,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 2.1,
    flagshipProjects: ['Palm Jumeirah', 'Palm Jebel Ali', 'Dubai Islands'],
    renderUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Sovereign Waterfront Archipelagos, Mega Coastal Fronds & Island Mansions',
    provenance: {
      source: 'Dubai Holding Master Disclosure & RERA Registry',
      citation: 'Dubai Holding Real Estate Strategic Audit 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_meraas',
    name: 'Meraas',
    tier: 'TIER_1_PREMIER',
    rating: 'AA+',
    deliveryTrackRecordPercent: 96.2,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 1.8,
    flagshipProjects: ['City Walk', 'Bluewaters Island', 'Port de La Mer', 'Bvlgari Residences'],
    renderUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Low-Density European Coastal Luxury, Jumeirah Bay Islands & Branded Trophy Assets',
    provenance: {
      source: 'Dubai Land Department & RERA Developer Scorecard',
      citation: 'RERA Master Developer Audits 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_sobha',
    name: 'Sobha Realty',
    tier: 'TIER_1_PRIVATE_BACKWARD_INTEGRATED',
    rating: 'AA+',
    deliveryTrackRecordPercent: 98.6,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 0.4,
    flagshipProjects: ['Sobha Hartland', 'Sobha Hartland II', 'Sobha Siniya Island'],
    renderUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Backward-Integrated In-House Construction, Forest Lagoon Sanctuaries & Precision Craftsmanship',
    provenance: {
      source: 'Sobha Group Audits & DLD Construction Progress Monitoring',
      citation: 'DLD Project Tracking System (PTS) 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_aldar',
    name: 'Aldar Properties',
    tier: 'TIER_1_GOVERNMENT_BACKED',
    rating: 'AAA',
    deliveryTrackRecordPercent: 96.5,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 1.4,
    flagshipProjects: ['Saadiyat Cultural District', 'Yas Island', 'Haven Dubailand'],
    renderUrl: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Abu Dhabi Cultural District Masterplans, Institutional Asset Governance & Biophilic Wellness Communities',
    provenance: {
      source: 'ADX Disclosures & ADGM/DLD Compliance Framework',
      citation: 'Aldar Properties PJSC Statutory Filing 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_damac',
    name: 'DAMAC Properties',
    tier: 'TIER_1_PRIVATE_HIGH_VOLUME',
    rating: 'AA-',
    deliveryTrackRecordPercent: 91.2,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 4.8,
    flagshipProjects: ['DAMAC Hills', 'DAMAC Lagoons', 'Safa Two', 'DAMAC Islands'],
    renderUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Themed Resort Lagoon Communities & High-Concept Italian Fashion Co-Branded Towers',
    provenance: {
      source: 'DLD PTS & RERA Trust Account Registry',
      citation: 'RERA Master Developer Audits 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_select',
    name: 'Select Group',
    tier: 'TIER_1_WATERFRONT_PREMIER',
    rating: 'AA',
    deliveryTrackRecordPercent: 96.8,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 1.5,
    flagshipProjects: ['Six Senses Residences Dubai Marina', 'Peninsula Business Bay', 'Marina Gate'],
    renderUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Trophy Waterfront High-Rises, Marina Gate Towers & Six Senses Hospitality Partnerships',
    provenance: {
      source: 'DLD PTS & Institutional Escrow Audits',
      citation: 'Select Group Portfolio Governance 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_ellington',
    name: 'Ellington Properties',
    tier: 'TIER_1_BOUTIQUE_LUXURY',
    rating: 'AA',
    deliveryTrackRecordPercent: 97.8,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 0.8,
    flagshipProjects: ['DT1', 'Wilton Terraces', 'Ocean House Palm Jumeirah', 'Ellington House'],
    renderUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Boutique Design-Led Residences, Resort Amenities & High-Yield Rental Premiums',
    provenance: {
      source: 'DLD PTS & RERA Escrow Audit',
      citation: 'RERA Trust Account Monitoring 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
  {
    id: 'dev_binghatti',
    name: 'Binghatti Developers',
    tier: 'TIER_1_BRANDED_FAST_TRACK',
    rating: 'AA-',
    deliveryTrackRecordPercent: 94.5,
    escrowCompliance: 'STRICT_FULL',
    averageCompletionDelayMonths: 1.1,
    flagshipProjects: ['Bugatti Residences', 'Mercedes-Benz Places', 'Burj Binghatti Jacob & Co'],
    renderUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1600&q=85',
    architecturalFocus: 'Hyper-Speed Construction Cycles & Global Luxury Branded Megatowers (Bugatti, Mercedes-Benz, Jacob & Co)',
    provenance: {
      source: 'DLD PTS & RERA Fast-Track Construction Registry',
      citation: 'DLD Developer Performance Tracker 2026',
      authorityWeight: AuthorityLevel.STATUTORY,
      lastVerified: '2026-08-01T00:00:00.000Z',
    },
  },
];
